import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests from "../utils/requests";

export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="http://assetshuluimcom-a.akamaihd.net/h3o/icons/favicon.ico.png"
        />
      </Head>

      <Header />

      <Nav />

      <Results results={results} />
    </div>
  );
}

Home.displayName = "Home";

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((result) => result.json());

  return {
    props: {
      results: request.results,
    },
  };
}
